apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: northamerica-northeast1-docker.pkg.dev/third-diorama-459405-q0/simple-api-repo/simple-api
      context: .
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    gitCommit: {}
manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/service.yaml
deploy:
  clouddeploy: {}