apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
    spec:
      containers:
        - name: simple-api
          image: northamerica-northeast1-docker.pkg.dev/third-diorama-459405-q0/simple-api-repo/simple-api:v1
          ports:
            - containerPort: 8080