name: Code Coverage Java
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    types: [ synchronize, opened, reopened, edited ]

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Build and generate coverage
        run: mvn clean test

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/*