name: Non Prod CI/CD Pipeline
on:
  workflow_run:
    workflows: ['Verify Build']
    types:
      - completed
    branches:
      - 'main'
  workflow_dispatch:

env:
  PROJECT_ID: third-diorama-459405-q0
  REGION: northamerica-northeast1
  DELIVERY_PIPELINE_NAME: simple-api-pipeline

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: write  # Grant write permissions for pushing tags
    outputs:
      releasetag: ${{ steps.release.outputs.new_tag }}
      repotag: ${{ steps.tagging.outputs.new_tag }}
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create tag
        id: tagging
        run: |
          git tag v1.0.${{ github.run_number }}
          git push origin v1.0.${{ github.run_number }}
          echo "new_tag=v1.0.${{ github.run_number }}" >> $GITHUB_OUTPUT